#!/usr/bin/env python3 

# TODO: What happens when MAGIC or VERSION fail?
# TODO: What happens when packet size < 12?
# TODO: Why is time.sleep so SLOW?

import random
from packet import *
import socket
from socket import *
import sys
import threading
from threading import *
import time

import os

serverName = None
serverPort = None
clientSocket = socket(AF_INET, SOCK_DGRAM)
shutdown_time = threading.Event()
alive_rcv = False

def send(command, seq_num, session_id, data=None):
    packet = wrap_packet(command, seq_num, session_id, data)
    clientSocket.sendto(packet,(serverName, serverPort))

def receive():
    packet, serverAddress = clientSocket.recvfrom(2048)
    return unwrap_packet(packet)

def close_session():
    try:
        clientSocket.shutdown(SHUT_WR)
    except:
        pass
    clientSocket.close()

def timer_goodbye():
    timeout = 5
    cycles = 1000
    
    i = 0
    while i < timeout * cycles / 5: # way too slow, using a magic number
        time.sleep(timeout / cycles)
        if (alive_rcv):
            i = 0
        else:
            i += 1
    close_session()
    shutdown_time.set()


def handle_keyboard(session_id):
    seq_num = 1
    while True:
        data = sys.stdin.readline()
        if (not data or (data == "q\n" and sys.stdin.isatty())):
            send(Command.GOODBYE, seq_num, session_id, None)
            break
        else:
            send(Command.DATA, seq_num, session_id, data)
            global alive_rcv
            alive_rcv = False

        seq_num += 1
    shutdown_time.set()

def handle_socket():
    while True:
        magic, version, command, sequence, session_id, data = receive()
        if (command == Command.GOODBYE):
            print('closing client')
        if (command != Command.ALIVE):
            break
        else:
            global alive_rcv
            alive_rcv = True
    shutdown_time.set()

'''
The main socket loop

Corner cases -
    ???      | packet < 12 bytes (not P0P packet)
    ???      | magic != MAGIC or version != VERSION
    Goodbye  | server sends incorrect session id
'''
def start_client(session_id):
    timer = Thread(target=timer_goodbye, daemon=True)
    timer.start()
    send(Command.HELLO, 0, session_id)
    
    magic, version, command, _, rcv_id, _ = receive()
    if command == Command.HELLO and rcv_id == session_id:
        global alive_rcv
        alive_rcv = True

        # Start the main running threads
        t1 = Thread(target=handle_socket, daemon=True)
        t2 = Thread(target=handle_keyboard, args=(session_id,), daemon=True)
        t1.start()
        t2.start()
    else:
        shutdown_time.set()

if __name__ == '__main__':
    serverName = sys.argv[1]
    serverPort = int(sys.argv[2])
    
    session_id = random.randint(0x00000000, 0xFFFFFFFF)

    # Start
    t0 = Thread(target=start_client, args=(session_id,), daemon=True)
    t0.start()
    shutdown_time.wait()
    close_session()
